version: '3.8'

services:
  # TimescaleDB (PostgreSQL) service
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: perocube-postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/scripts:/scripts
      - ./db/sql:/sql
      - ./db/sql/schema:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local