apiVersion: 1

datasources:
  - name: outdoor_monitoring
    type: postgres
    access: proxy
    uid: outdoor-monitoring
    url: timescaledb:5432
    database: outdoor_monitoring
    user: postgres
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: true
    isDefault: false
    editable: true
