apiVersion: 1

deleteDatasources:
  - name: TimescaleDB
    orgId: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    uid: perocube-timescaledb
    url: timescaledb:5432
    database: perocube
    user: postgres
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
