version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/perocube.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  # Root logger
  "":
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: True

  # Database-related logger
  "database":
    level: INFO
    handlers: [console, file]
    propagate: False

  # API-related logger
  "api":
    level: INFO
    handlers: [console, file]
    propagate: False

  # Data processing logger
  "data_processing":
    level: DEBUG
    handlers: [console, file]
    propagate: False

  # Ingestion logger
  "ingestion":
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: False

  # Third-party loggers
  "urllib3":
    level: WARNING
    handlers: [console]
    propagate: False

  "psycopg2":
    level: WARNING
    handlers: [console]
    propagate: False