engine.name=cloud-000
group.id=cloud
external.id=000
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://timescaledb-cloud:5432/perocube
db.user=postgres
db.password=postgres
auto.registration=true
registration.url=
sync.url=http://symmetricds-cloud:31415/sync/cloud-000
auto.reload=true
