engine.name=edge-001
group.id=edge
external.id=001
registration.url=http://nomad02.csn32.bessy.de:31415/sync/cloud-000
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://timescaledb:5432/perocube
db.user=postgres
db.password=postgres
job.routing.period.time.ms=5000
job.push.period.time.ms=10000
job.pull.period.time.ms=10000
