name: Build and Push Jupyter Docker Image

# This workflow runs on any push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard GitHub-hosted runner
    permissions:
      contents: read
      packages: write # Grant permission to push the image to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # This is a secure, automatic token

      - name: Build and push Jupyter image
        uses: docker/build-push-action@v5
        with:
          context: ./jupyter # Specifies that the Dockerfile is in the 'jupyter' directory
          push: true
          tags: ghcr.io/paolog8/perocube-jupyter:latest # The full name for your image
